# Generated by Django 3.2 on 2021-04-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doviz_ismi', models.CharField(max_length=10)),
                ('alis', models.FloatField()),
                ('satis', models.FloatField()),
                ('fark', models.FloatField()),
                ('kur_kodu', models.CharField(max_length=10)),
            ],
        ),
    ]
